// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package sys_service

import (
	"context"

	"github.com/SupenBysz/gf-admin-community/sys_model"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IBizCtx interface {
		Init(r *ghttp.Request, customCtx *sys_model.Context)
		Get(ctx context.Context) *sys_model.Context
		SetUser(ctx context.Context, claimsUser *sys_model.JwtCustomClaims)
	}
)

var (
	localBizCtx IBizCtx
)

func BizCtx() IBizCtx {
	if localBizCtx == nil {
		// 记录错误但不panic，让调用方处理
		g.Log().Error(context.Background(), "IBizCtx服务未注册，请检查服务初始化顺序")
		return nil
	}
	return localBizCtx
}

func RegisterBizCtx(i IBizCtx) {
	localBizCtx = i
}
